version: '3.8'
services:
  cache:
    container_name: redis
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    volumes:
      - cache:/data
  db:
    image: postgres:14-bookworm
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - '2345:5432'
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USERNAME}
  rails:
    image: yakbakrails
    ports:
      - '3000:3000'
    environment:
      - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DISCORD_CLIENT_SECRET=${DISCORD_CLIENT_SECRET}
      - VITE_DISCORD_CLIENT_ID=${VITE_DISCORD_CLIENT_ID}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - DATABASE_URL=${DATABASE_URL}
volumes:
  cache:
    driver: local
  db:
    driver: local